export const FETCH_ALL_SCHOOLS = 'FETCH_ALL_SCHOOLS';
export const DELETE_STUDY = 'DELETE_STUDY';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_FIRST_NAME = 'SET_FIRST_NAME';
export const SET_LAST_NAME = 'SET_LAST_NAME';
export const SET_EDUCATION = 'SET_EDUCATION';
export const CLEAR_ALL_SCHOOLS = 'CLEAR_ALL_SCHOOLS';